CREATE TABLE [dbo].[DecisionForSolider] (
    [DecisionID]          INT             IDENTITY (1, 1) NOT NULL,
    [DecisionTypeID_FK]   INT             NULL,
    [DecisionStateID_FK]  INT             NULL,
    [userID_FK]           INT             NULL,
    [DecisionNo]          INT             NULL,
    [DecisionDate]        DATETIME        NULL,
    [DecisionTitle]       NVARCHAR (150)  NULL,
    [DecisionFromSoruce]  NVARCHAR (150)  NULL,
    [DecisionToSoruce]    NVARCHAR (150)  NULL,
    [DecisionFromDate]    DATETIME        NULL,
    [DecisionToDate]      DATETIME        NULL,
    [DecisionStartDate]   DATETIME        NULL,
    [DecisionPeriod]      INT             NULL,
    [DecisionType1]       INT             NULL,
    [DecisionType2]       INT             NULL,
    [DecisionType3]       INT             NULL,
    [DecisionText1]       NVARCHAR (400)  NULL,
    [DecisionText2]       NVARCHAR (400)  NULL,
    [DecisionText3]       NVARCHAR (400)  NULL,
    [DecisionText4]       NVARCHAR (400)  NULL,
    [DecisionText5]       NVARCHAR (400)  NULL,
    [DecisionText6]       NVARCHAR (400)  NULL,
    [DecisionText7]       NVARCHAR (400)  NULL,
    [DecisionText8]       NVARCHAR (400)  NULL,
    [DecisionText9]       NVARCHAR (400)  NULL,
    [DecisionDescription] NVARCHAR (4000) NULL,
    [entryDate]           DATETIME        CONSTRAINT [DF_DecisionForSolider_entryDate] DEFAULT (getdate()) NULL,
    [entryData]           NVARCHAR (20)   NULL,
    [hostName]            NVARCHAR (200)  NULL
);

