CREATE TABLE [dbo].[Document] (
    [documentID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [transactionID_FK]     BIGINT          NULL,
    [documentTypeID_FK]    INT             NULL,
    [documentStateID_FK]   INT             NULL,
    [userID_FK]            INT             NULL,
    [documentNo]           INT             NULL,
    [documentDate]         DATETIME        NULL,
    [documentTitle]        NVARCHAR (150)  NULL,
    [documentFromSoruce]   NVARCHAR (150)  NULL,
    [documentToSoruce]     NVARCHAR (150)  NULL,
    [documentFromDate]     DATETIME        NULL,
    [documentToDate]       DATETIME        NULL,
    [documentStartDate]    DATETIME        NULL,
    [documentPeriod]       INT             NULL,
    [documentType1]        INT             NULL,
    [documentType2]        INT             NULL,
    [documentType3]        INT             NULL,
    [documentText1]        NVARCHAR (400)  NULL,
    [documentText2]        NVARCHAR (400)  NULL,
    [documentText3]        NVARCHAR (400)  NULL,
    [documentText4]        NVARCHAR (400)  NULL,
    [documentText5]        NVARCHAR (400)  NULL,
    [documentText6]        NVARCHAR (400)  NULL,
    [documentText7]        NVARCHAR (400)  NULL,
    [documentText8]        NVARCHAR (400)  NULL,
    [documentText9]        NVARCHAR (400)  NULL,
    [documentInt1]         INT             NULL,
    [documentInt2]         INT             NULL,
    [documentInt3]         INT             NULL,
    [documentInt4]         INT             NULL,
    [documentDate1]        DATETIME        NULL,
    [documentDate2]        DATETIME        NULL,
    [documentDate3]        DATETIME        NULL,
    [documentDate4]        DATETIME        NULL,
    [documentDate5]        DATETIME        NULL,
    [documentDecimal1]     DECIMAL (18, 2) NULL,
    [documentDecimal2]     DECIMAL (18, 2) NULL,
    [documentDecimal3]     DECIMAL (18, 2) NULL,
    [documentDecimal4]     DECIMAL (18, 2) NULL,
    [documentDescription]  NVARCHAR (4000) NULL,
    [documentParentID]     BIGINT          NULL,
    [documentCanceledByID] BIGINT          NULL,
    [documentUpdetedByID]  BIGINT          NULL,
    [documentInsertedBy]   NVARCHAR (500)  NULL,
    [documentActive]       BIT             NULL,
    [entryDate]            DATETIME        CONSTRAINT [DF_Document_entryDate] DEFAULT (getdate()) NULL,
    [entryData]            NVARCHAR (20)   NULL,
    [hostName]             NVARCHAR (200)  CONSTRAINT [DF_Document_hostName] DEFAULT (host_name()) NULL,
    CONSTRAINT [PK_Document] PRIMARY KEY CLUSTERED ([documentID] ASC),
    CONSTRAINT [FK_Document_DocumentState] FOREIGN KEY ([documentStateID_FK]) REFERENCES [dbo].[DocumentState] ([documentStateID]),
    CONSTRAINT [FK_Document_DocumentType] FOREIGN KEY ([documentTypeID_FK]) REFERENCES [dbo].[DocumentType] ([documentTypeID]),
    CONSTRAINT [FK_Document_Transaction] FOREIGN KEY ([transactionID_FK]) REFERENCES [dbo].[Transactions] ([transactionID])
);

