CREATE TABLE [dbo].[KFMCReportsHeader] (
    [KFMCReportsHeaderID]        INT            IDENTITY (1, 1) NOT NULL,
    [KFMCReportsHeaderLargeLogo] IMAGE          NULL,
    [KFMCReportsHeaderSmallLogo] IMAGE          NULL,
    [KFMCReportsHeaderIconLogo]  IMAGE          NULL,
    [KFMCReportsHeaderText1]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText2]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText3]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText4]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText5]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText6]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText7]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText8]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText9]     NVARCHAR (200) NULL,
    [KFMCReportsHeaderText10]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText11]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText12]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText13]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText14]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText15]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText16]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText17]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText18]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText19]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderText20]    NVARCHAR (200) NULL,
    [KFMCReportsHeaderFullText]  NVARCHAR (200) NULL,
    [startDate]                  DATE           NULL,
    [EndDate]                    DATE           NULL,
    [active]                     BIT            NULL,
    CONSTRAINT [PK_KFMCReportsHeader] PRIMARY KEY CLUSTERED ([KFMCReportsHeaderID] ASC)
);

