CREATE TABLE [dbo].[UserTemp] (
    [id_]                  INT              IDENTITY (1, 1) NOT NULL,
    [IDUID]                UNIQUEIDENTIFIER CONSTRAINT [DF_UserTemp_IDUID] DEFAULT (newid()) NOT NULL,
    [userID_FK]            INT              NOT NULL,
    [fristName_A]          NVARCHAR (20)    NULL,
    [secondName_A]         NVARCHAR (20)    NULL,
    [thirdName_A]          NVARCHAR (20)    NULL,
    [forthName_A]          NVARCHAR (20)    NULL,
    [lastName_A]           NVARCHAR (20)    NULL,
    [fristName_E]          NVARCHAR (20)    NULL,
    [secondName_E]         NVARCHAR (20)    NULL,
    [thirdName_E]          NVARCHAR (20)    NULL,
    [forthName_E]          NVARCHAR (20)    NULL,
    [lastName_E]           NVARCHAR (20)    NULL,
    [IDNumber]             NVARCHAR (10)    NULL,
    [IDExpiryDate]         DATE             NULL,
    [dateOfBirth]          DATE             NULL,
    [birthPlaceCityID_FK]  INT              NULL,
    [fno]                  NVARCHAR (50)    NULL,
    [jobNo]                INT              NULL,
    [jobSeq]               INT              NULL,
    [job_FK]               INT              NULL,
    [jobCode]              NVARCHAR (50)    NULL,
    [rankID_FK]            INT              NULL,
    [dsdID_FK]             INT              NULL,
    [housephoneNo]         NVARCHAR (20)    NULL,
    [mobileNo]             NVARCHAR (20)    NULL,
    [nearName]             NVARCHAR (200)   NULL,
    [nearMobileNo]         NVARCHAR (20)    NULL,
    [emailAddress]         NVARCHAR (100)   NULL,
    [nationalAddressShort] NVARCHAR (10)    NULL,
    [nationalAddress]      NVARCHAR (1000)  NULL,
    [contractStartDate]    DATETIME         NULL,
    [educationID_FK]       INT              NULL,
    [educationName]        NVARCHAR (200)   NULL,
    [Description]          NVARCHAR (1000)  NULL,
    [DoucumentHandeld]     INT              CONSTRAINT [DF_UserTemp_DoucumentHandeld] DEFAULT ((0)) NULL,
    [entryDate]            DATETIME         CONSTRAINT [DF_UserTemp_entryDate] DEFAULT (getdate()) NULL,
    [entryData]            NVARCHAR (20)    NULL,
    [hostName]             NVARCHAR (200)   NULL,
    CONSTRAINT [PK_UserTemp] PRIMARY KEY CLUSTERED ([userID_FK] ASC)
);

