CREATE TABLE [Maintenance].[BuildingMaintenanceRequest] (
    [RequestID]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [IdaraId_FK]            BIGINT         NOT NULL,
    [RequestNo]             NVARCHAR (50)  NULL,
    [ParentRequestID]       BIGINT         NULL,
    [RootRequestID]         BIGINT         NULL,
    [RequestLevel]          INT            CONSTRAINT [DF_BuildingMaintenanceRequest_RequestLevel] DEFAULT ((0)) NOT NULL,
    [IsSubRequest]          BIT            CONSTRAINT [DF_BuildingMaintenanceRequest_IsSubRequest] DEFAULT ((0)) NOT NULL,
    [IsBlockingParent]      BIT            CONSTRAINT [DF_BuildingMaintenanceRequest_IsBlockingParent] DEFAULT ((1)) NOT NULL,
    [BuildingID]            BIGINT         NULL,
    [UnitID]                BIGINT         NULL,
    [ResidentID]            BIGINT         NULL,
    [MaintenanceCategoryID] BIGINT         NOT NULL,
    [CurrentDSDID]          BIGINT         NULL,
    [OriginalDSDID]         BIGINT         NULL,
    [StatusID]              INT            NOT NULL,
    [PriorityID]            INT            NOT NULL,
    [Description_A]         NVARCHAR (MAX) NOT NULL,
    [HasDispute]            BIT            CONSTRAINT [DF_BuildingMaintenanceRequest_HasDispute] DEFAULT ((0)) NOT NULL,
    [DisputeStatusID]       INT            NULL,
    [EscalationLevel]       INT            CONSTRAINT [DF_BuildingMaintenanceRequest_EscalationLevel] DEFAULT ((0)) NOT NULL,
    [IsLockedByDecision]    BIT            CONSTRAINT [DF_BuildingMaintenanceRequest_IsLockedByDecision] DEFAULT ((0)) NOT NULL,
    [RequestDate]           DATETIME       CONSTRAINT [DF_BuildingMaintenanceRequest_RequestDate] DEFAULT (getdate()) NOT NULL,
    [ClosedDate]            DATETIME       NULL,
    [entryUser]             BIGINT         NULL,
    [entryDate]             DATETIME       CONSTRAINT [DF_BuildingMaintenanceRequest_entryDate] DEFAULT (getdate()) NOT NULL,
    [updateUser]            BIGINT         NULL,
    [updateDate]            DATETIME       NULL,
    [IsActive]              BIT            CONSTRAINT [DF_BuildingMaintenanceRequest_IsActive] DEFAULT ((1)) NOT NULL,
    [entryData]             NVARCHAR (20)  NULL,
    [hostName]              NVARCHAR (200) NULL,
    [TransactionID_FK]      BIGINT         NULL,
    CONSTRAINT [PK_BuildingMaintenanceRequest] PRIMARY KEY CLUSTERED ([RequestID] ASC),
    CONSTRAINT [FK_BuildingMaintenanceRequest_DeptSecDiv_Current] FOREIGN KEY ([CurrentDSDID]) REFERENCES [dbo].[DeptSecDiv] ([DSDID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_DeptSecDiv_Original] FOREIGN KEY ([OriginalDSDID]) REFERENCES [dbo].[DeptSecDiv] ([DSDID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_DisputeStatus] FOREIGN KEY ([DisputeStatusID]) REFERENCES [Maintenance].[MaintenanceRequestStatus] ([StatusID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_MaintenanceCategory] FOREIGN KEY ([IdaraId_FK], [MaintenanceCategoryID]) REFERENCES [Maintenance].[MaintenanceCategory] ([IdaraId_FK], [MaintenanceCategoryID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_ParentRequest] FOREIGN KEY ([ParentRequestID]) REFERENCES [Maintenance].[BuildingMaintenanceRequest] ([RequestID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_Priority] FOREIGN KEY ([PriorityID]) REFERENCES [Maintenance].[MaintenancePriority] ([PriorityID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_RootRequest] FOREIGN KEY ([RootRequestID]) REFERENCES [Maintenance].[BuildingMaintenanceRequest] ([RequestID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_Status] FOREIGN KEY ([StatusID]) REFERENCES [Maintenance].[MaintenanceRequestStatus] ([StatusID]),
    CONSTRAINT [FK_BuildingMaintenanceRequest_Transactions] FOREIGN KEY ([TransactionID_FK]) REFERENCES [dbo].[Transactions] ([transactionID])
);

