CREATE TABLE [support].[Ticket] (
    [ticketID]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [ticketNo]                  NVARCHAR (30)  NOT NULL,
    [ticketTypeID_FK]           TINYINT        NOT NULL,
    [priorityID_FK]             TINYINT        CONSTRAINT [DF_support_Ticket_priorityID] DEFAULT ((2)) NOT NULL,
    [statusID_FK]               TINYINT        CONSTRAINT [DF_support_Ticket_statusID] DEFAULT ((1)) NOT NULL,
    [ticketTitle]               NVARCHAR (300) NOT NULL,
    [ticketDescription]         NVARCHAR (MAX) NOT NULL,
    [affectedPageName]          NVARCHAR (200) NULL,
    [affectedPageUrl]           NVARCHAR (500) NULL,
    [affectedActionName]        NVARCHAR (200) NULL,
    [errorDetails]              NVARCHAR (MAX) NULL,
    [createdByUserID_FK]        BIGINT         NOT NULL,
    [assignedToTeamMemberID_FK] BIGINT         NULL,
    [assignedByUserID_FK]       BIGINT         NULL,
    [assignedDate]              DATETIME       NULL,
    [closedDate]                DATETIME       NULL,
    [ticketActive]              BIT            CONSTRAINT [DF_support_Ticket_Active] DEFAULT ((1)) NOT NULL,
    [entryDate]                 DATETIME       CONSTRAINT [DF_support_Ticket_entryDate] DEFAULT (getdate()) NULL,
    [entryData]                 NVARCHAR (20)  NULL,
    [hostName]                  NVARCHAR (200) CONSTRAINT [DF_support_Ticket_hostName] DEFAULT (host_name()) NULL,
    CONSTRAINT [PK_support_Ticket] PRIMARY KEY CLUSTERED ([ticketID] ASC),
    CONSTRAINT [CK_support_Ticket_TypeRequirements] CHECK (([ticketTypeID_FK]=(2) OR [ticketTypeID_FK]=(1)) AND nullif(ltrim(rtrim(isnull([affectedPageName],N''))),N'') IS NULL AND nullif(ltrim(rtrim(isnull([affectedPageUrl],N''))),N'') IS NULL AND nullif(ltrim(rtrim(isnull([affectedActionName],N''))),N'') IS NULL OR [ticketTypeID_FK]=(3) AND (nullif(ltrim(rtrim(isnull([affectedPageName],N''))),N'') IS NOT NULL OR nullif(ltrim(rtrim(isnull([affectedPageUrl],N''))),N'') IS NOT NULL) AND nullif(ltrim(rtrim(isnull([affectedActionName],N''))),N'') IS NULL OR [ticketTypeID_FK]=(4) AND (nullif(ltrim(rtrim(isnull([affectedPageName],N''))),N'') IS NOT NULL OR nullif(ltrim(rtrim(isnull([affectedPageUrl],N''))),N'') IS NOT NULL) AND nullif(ltrim(rtrim(isnull([affectedActionName],N''))),N'') IS NOT NULL),
    CONSTRAINT [FK_support_Ticket_AssignedByUser] FOREIGN KEY ([assignedByUserID_FK]) REFERENCES [dbo].[Users] ([usersID]),
    CONSTRAINT [FK_support_Ticket_AssignedToMember] FOREIGN KEY ([assignedToTeamMemberID_FK]) REFERENCES [support].[TeamMember] ([teamMemberID]),
    CONSTRAINT [FK_support_Ticket_CreatedByUser] FOREIGN KEY ([createdByUserID_FK]) REFERENCES [dbo].[Users] ([usersID]),
    CONSTRAINT [FK_support_Ticket_Priority] FOREIGN KEY ([priorityID_FK]) REFERENCES [support].[TicketPriority] ([priorityID]),
    CONSTRAINT [FK_support_Ticket_Status] FOREIGN KEY ([statusID_FK]) REFERENCES [support].[TicketStatus] ([statusID]),
    CONSTRAINT [FK_support_Ticket_TicketType] FOREIGN KEY ([ticketTypeID_FK]) REFERENCES [support].[TicketType] ([ticketTypeID]),
    CONSTRAINT [UQ_support_Ticket_ticketNo] UNIQUE NONCLUSTERED ([ticketNo] ASC)
);

