CREATE TABLE [VIC].[Vehicles] (
    [vehicleID]             INT             IDENTITY (1, 1) NOT NULL,
    [ownerID_FK]            NVARCHAR (50)   NULL,
    [ManufacturerNameID_FK] INT             NULL,
    [vehicleModelID_FK]     INT             NULL,
    [vehicleClassID_FK]     INT             NULL,
    [TypeOfUseID_FK]        INT             NULL,
    [vehicleColorID_FK]     INT             NULL,
    [countryMadeID_FK]      INT             NULL,
    [regstritionTypeID_FK]  INT             NULL,
    [regionID_FK]           INT             NULL,
    [fuelTypeID_FK]         INT             NULL,
    [vehicleTypeID_FK]      INT             NULL,
    [yearModel]             INT             NULL,
    [capacity]              INT             NULL,
    [chassisNumber]         NVARCHAR (100)  NOT NULL,
    [serialNumber]          NVARCHAR (50)   NULL,
    [plateLetters]          NVARCHAR (50)   NULL,
    [plateNumbers]          INT             NULL,
    [armyNumber]            NVARCHAR (50)   NULL,
    [vehicleNote]           NVARCHAR (400)  NULL,
    [entryDate]             DATETIME        CONSTRAINT [DF_Vehicles_entryDate] DEFAULT (getdate()) NULL,
    [entryData]             NVARCHAR (20)   NULL,
    [hostName]              NVARCHAR (200)  NULL,
    [isActive]              BIT             CONSTRAINT [DF_Vehicles_isActive] DEFAULT ((1)) NOT NULL,
    [IdaraID_FK]            BIGINT          NOT NULL,
    [vehicleStatusID_FK]    INT             NULL,
    [scrapDate]             DATETIME        NULL,
    [scrapRefNo]            NVARCHAR (100)  NULL,
    [scrapReason]           NVARCHAR (400)  NULL,
    [scrapNote]             NVARCHAR (1000) NULL,
    CONSTRAINT [PK_Vehicles] PRIMARY KEY CLUSTERED ([chassisNumber] ASC),
    CONSTRAINT [FK_Vehicles_Idara] FOREIGN KEY ([IdaraID_FK]) REFERENCES [dbo].[Idara] ([idaraID])
);

