CREATE TABLE [Housing].[batest] (
    [buildingActionID]              BIGINT           IDENTITY (1, 1) NOT NULL,
    [buildingActionUDID]            UNIQUEIDENTIFIER NULL,
    [buildingActionTypeID_FK]       INT              NULL,
    [buildingStatusID_FK]           INT              NULL,
    [generalNo_FK]                  INT              NULL,
    [buildingPaymentTypeID_FK]      INT              NULL,
    [buildingDetailsNo]             NVARCHAR (20)    NULL,
    [buildingActionFromDate]        DATETIME         NULL,
    [buildingActionToDate]          DATETIME         NULL,
    [buildingActionDate]            DATETIME         NULL,
    [buildingActionDate2]           DATETIME         NULL,
    [buildingActionDecisionNo]      NVARCHAR (20)    NULL,
    [buildingActionDecisionDate]    DATETIME         NULL,
    [fromDSD_FK]                    INT              NULL,
    [toDSD_FK]                      INT              NULL,
    [buildingActionFromSourceID_FK] INT              NULL,
    [buildingActionToSourceID_FK]   INT              NULL,
    [buildingActionNote]            NVARCHAR (1000)  NULL,
    [buildingActionExtraText1]      NVARCHAR (200)   NULL,
    [buildingActionExtraText2]      NVARCHAR (200)   NULL,
    [buildingActionExtraText3]      NVARCHAR (200)   NULL,
    [buildingActionExtraDate1]      DATETIME         NULL,
    [buildingActionExtraDate2]      DATETIME         NULL,
    [buildingActionExtraDate3]      DATETIME         NULL,
    [buildingActionExtraFloat1]     FLOAT (53)       NULL,
    [buildingActionExtraFloat2]     FLOAT (53)       NULL,
    [buildingActionExtraInt1]       INT              NULL,
    [buildingActionExtraInt2]       INT              NULL,
    [buildingActionExtraInt3]       INT              NULL,
    [buildingActionExtraType1]      INT              NULL,
    [buildingActionExtraType2]      INT              NULL,
    [buildingActionExtraType3]      INT              NULL,
    [entryDate]                     DATETIME         NULL,
    [entryData]                     NVARCHAR (20)    NULL,
    [hostName]                      NVARCHAR (200)   NULL,
    CONSTRAINT [PK_batest1] PRIMARY KEY CLUSTERED ([buildingActionID] ASC)
);

