CREATE TABLE [Housing].[OccupantCustodyAction] (
    [occupantCustodyActionID]        INT             IDENTITY (1, 1) NOT NULL,
    [buildingActionID_FK]            BIGINT          NULL,
    [custodyActionTypeID_FK]         INT             NULL,
    [custodyItemID_FK]               INT             NULL,
    [custodyStatusID_FK]             INT             NULL,
    [buildingActionID_Parent]        BIGINT          NULL,
    [occupantCustodyActionID_Parent] INT             NULL,
    [occupantCustodyActionActive]    BIT             NULL,
    [occupantCustodyActionNote]      NVARCHAR (1000) NULL,
    [occupantCustodyActionPenalty]   DECIMAL (18, 2) NULL,
    [custodyOrDamageTypeID_FK]       INT             NULL,
    [Paid]                           BIT             NULL,
    [PaidBy]                         NVARCHAR (500)  NULL,
    [PaidNumber]                     NVARCHAR (100)  NULL,
    [PaidPaymentType]                INT             NULL,
    [canceldBy]                      NVARCHAR (500)  NULL,
    [updatedby]                      NVARCHAR (500)  NULL,
    [spForAction]                    NVARCHAR (1000) NULL,
    [entryDate]                      DATETIME        CONSTRAINT [DF_OccupantCustodyAction_entryDate] DEFAULT (getdate()) NULL,
    [entryData]                      NVARCHAR (20)   NULL,
    [hostName]                       NVARCHAR (200)  NULL,
    CONSTRAINT [PK_OccupantCustody] PRIMARY KEY CLUSTERED ([occupantCustodyActionID] ASC),
    CONSTRAINT [FK_OccupantCustody_BuildingAction] FOREIGN KEY ([buildingActionID_FK]) REFERENCES [Housing].[BuildingAction] ([buildingActionID]),
    CONSTRAINT [FK_OccupantCustody_CustodyActionType] FOREIGN KEY ([custodyActionTypeID_FK]) REFERENCES [Housing].[CustodyActionType] ([custodyActionTypeID]),
    CONSTRAINT [FK_OccupantCustody_CustodyItems] FOREIGN KEY ([custodyItemID_FK]) REFERENCES [Housing].[CustodyItems] ([custodyItemID]),
    CONSTRAINT [FK_OccupantCustody_CustodyStatus] FOREIGN KEY ([custodyStatusID_FK]) REFERENCES [Housing].[CustodyStatus] ([custodyStatusID]),
    CONSTRAINT [FK_OccupantCustodyAction_BuildingAction] FOREIGN KEY ([buildingActionID_Parent]) REFERENCES [Housing].[BuildingAction] ([buildingActionID]),
    CONSTRAINT [FK_OccupantCustodyAction_CustodyOrDamageType] FOREIGN KEY ([custodyOrDamageTypeID_FK]) REFERENCES [Housing].[CustodyOrDamageType] ([custodyOrDamageTypeID]),
    CONSTRAINT [FK_OccupantCustodyAction_OccupantCustodyAction] FOREIGN KEY ([occupantCustodyActionID_Parent]) REFERENCES [Housing].[OccupantCustodyAction] ([occupantCustodyActionID])
);

