CREATE TABLE [Housing].[ResidentInfoTemp_] (
    [generalNo]             INT              NOT NULL,
    [birthdate]             DATE             NULL,
    [firstName_A]           NVARCHAR (50)    NULL,
    [firstName_E]           NVARCHAR (50)    NULL,
    [lastName_A]            NVARCHAR (50)    NULL,
    [lastName_E]            NVARCHAR (50)    NULL,
    [NationalID]            NVARCHAR (10)    NULL,
    [note]                  NVARCHAR (500)   NULL,
    [residentInfoActive]    BIT              NULL,
    [residentInfoID]        INT              NOT NULL,
    [residentInfoUID]       UNIQUEIDENTIFIER NOT NULL,
    [secondName_A]          NVARCHAR (50)    NULL,
    [secondName_E]          NVARCHAR (50)    NULL,
    [thirdName_A]           NVARCHAR (50)    NULL,
    [thirdName_E]           NVARCHAR (50)    NULL,
    [rankID_FK]             INT              NULL,
    [militaryUnitID_FK]     INT              NULL,
    [martialStatusID_FK]    INT              NULL,
    [dependinceCounter]     INT              NULL,
    [nationalityID_FK]      INT              NULL,
    [genderID_FK]           INT              NULL,
    [residentDetailsActive] BIT              NULL,
    [rankID]                INT              NOT NULL,
    [rankNameA]             NVARCHAR (100)   NULL,
    [userType_FK]           INT              NULL,
    [rankClassID_FK]        INT              NULL,
    [contanctTypeID_FK]     INT              NULL,
    [contactInfoID]         INT              NOT NULL,
    [contactDetails]        NVARCHAR (50)    NULL,
    [contactInfoActive]     BIT              NULL,
    [contactInfoEndDate]    DATETIME         NULL,
    [contactInfoStartDate]  DATETIME         NULL
);

