CREATE TABLE [Tickets].[Ticket] (
    [ticketID]                  BIGINT          IDENTITY (1, 1) NOT NULL,
    [IdaraID_FK]                BIGINT          NULL,
    [ticketNo]                  NVARCHAR (30)   NULL,
    [ticketClassID_FK]          INT             NULL,
    [operationalTypeID_FK]      INT             NULL,
    [ticketStatusID_FK]         INT             NULL,
    [requesterTypeID_FK]        INT             NULL,
    [serviceID_FK]              BIGINT          NULL,
    [UserID_FK]                 BIGINT          NULL,
    [residentInfoID_FK]         BIGINT          NULL,
    [OpenedByUsersID_FK]        BIGINT          NULL,
    [CurrentDSDID_FK]           BIGINT          NULL,
    [CurrentDistributorID_FK]   BIGINT          NULL,
    [AssignedToUsersID_FK]      BIGINT          NULL,
    [impactID_FK]               INT             NULL,
    [urgencyID_FK]              INT             NULL,
    [ticketPriorityID_FK]       INT             NULL,
    [resolutionTypeID_FK]       INT             NULL,
    [ParentTicketID_FK]         BIGINT          NULL,
    [RootTicketID_FK]           BIGINT          NULL,
    [ticketTitle]               NVARCHAR (500)  NULL,
    [ticketDescription]         NVARCHAR (4000) NULL,
    [otherServiceText]          NVARCHAR (500)  NULL,
    [resolutionNotes]           NVARCHAR (4000) NULL,
    [ticketIsMajorIncident]     BIT             NULL,
    [ticketOpendAt]             DATETIME        NULL,
    [ticketFirstRespondedAt]    DATETIME        NULL,
    [ticketResolvedAt]          DATETIME        NULL,
    [ticketClosedAt]            DATETIME        NULL,
    [ticketLastStatusChangedAt] DATETIME        NULL,
    [ticketActive]              BIT             NULL,
    CONSTRAINT [PK_Ticket] PRIMARY KEY CLUSTERED ([ticketID] ASC),
    CONSTRAINT [FK_Ticket_Idara] FOREIGN KEY ([IdaraID_FK]) REFERENCES [dbo].[Idara] ([idaraID]),
    CONSTRAINT [FK_Ticket_OperationalType] FOREIGN KEY ([operationalTypeID_FK]) REFERENCES [Tickets].[OperationalType] ([operationalTypeID]),
    CONSTRAINT [FK_Ticket_RequesterType] FOREIGN KEY ([requesterTypeID_FK]) REFERENCES [Tickets].[RequesterType] ([requesterTypeID]),
    CONSTRAINT [FK_Ticket_ResolutionType] FOREIGN KEY ([resolutionTypeID_FK]) REFERENCES [Tickets].[ResolutionType] ([resolutionTypeID]),
    CONSTRAINT [FK_Ticket_Service] FOREIGN KEY ([serviceID_FK]) REFERENCES [Tickets].[Service] ([serviceID]),
    CONSTRAINT [FK_Ticket_Ticket] FOREIGN KEY ([ParentTicketID_FK]) REFERENCES [Tickets].[Ticket] ([ticketID]),
    CONSTRAINT [FK_Ticket_Ticket1] FOREIGN KEY ([RootTicketID_FK]) REFERENCES [Tickets].[Ticket] ([ticketID]),
    CONSTRAINT [FK_Ticket_TicketClass] FOREIGN KEY ([ticketClassID_FK]) REFERENCES [Tickets].[TicketClass] ([ticketClassID]),
    CONSTRAINT [FK_Ticket_TicketImpact] FOREIGN KEY ([impactID_FK]) REFERENCES [Tickets].[TicketImpact] ([ticketImpactID]),
    CONSTRAINT [FK_Ticket_TicketPriority] FOREIGN KEY ([ticketPriorityID_FK]) REFERENCES [Tickets].[TicketPriority] ([ticketPriorityID]),
    CONSTRAINT [FK_Ticket_TicketStatus] FOREIGN KEY ([ticketStatusID_FK]) REFERENCES [Tickets].[TicketStatus] ([ticketStatusID]),
    CONSTRAINT [FK_Ticket_TicketUrgency] FOREIGN KEY ([urgencyID_FK]) REFERENCES [Tickets].[TicketUrgency] ([ticketUrgencyID])
);

